### ISSUE TITLE
Create basic entities based on new ER diagram.

### ISSUE THREAD

**Issue by tamminh2003** [tamminh2003/petCare#2]
See README.md

![image](https://user-images.githubusercontent.com/8927582/225273088-b1bbc156-fcf4-4a21-a25f-51c090ba7bdb.png)

**Comment by tamminh2003** [comment]
@kennguyen291 Minh sẽ viết Customer entity

**Comment by knguyen291** [comment]
I am adding and adjusting these fields as highlight

![Screen Shot 2023-03-17 at 8 47 44 pm](https://user-images.githubusercontent.com/58890818/225870637-0a7fb38c-db0c-4e12-bb79-795add81ed23.png)

**Comment by tamminh2003** [comment]
Please update the Repo Readme.md so everyone have the same view of entity diagram.
